-- Heat Check: Lv3 (Hot) cards, moved out of the client bundle.
-- Run once after the migration (SQL editor, or `supabase db seed`). Safe to re-run: skips cards that already exist.

insert into public.premium_cards (game, heat, text, optional_dare, extra)
values
  ('redflag', 3, 'They leave a slow trail of kisses down your neck in the elevator.', 'Kiss slowly from your partner''s jaw down to their collarbone, taking ten seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your partner pins your hands during a pillow fight, then just stares.', 'Gently pin your partner''s wrists against the couch and hold eye contact for fifteen seconds.', '{}'::jsonb),
  ('redflag', 3, 'They whisper exactly what they want to do later, at a family dinner.', 'Whisper in your partner''s ear what you want to do with them later tonight.', '{}'::jsonb),
  ('redflag', 3, 'Your date grabs your hips and pulls you closer on the dance floor.', 'Put your hands on your partner''s hips and pull them flush against you for twenty seconds.', '{}'::jsonb),
  ('redflag', 3, 'They kiss your inner wrist while holding eye contact across the table.', 'Kiss your partner''s inner wrist slowly while holding eye contact for ten seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your partner squeezes your thigh under the table at a fancy restaurant.', 'Rest your hand on your partner''s thigh over their clothes and squeeze slowly for fifteen seconds.', '{}'::jsonb),
  ('redflag', 3, 'They sit on your lap facing you at a friend''s party.', 'Sit on your partner''s lap facing them and hold eye contact for thirty seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your partner slides off your watch and says ''you won''t need this tonight.''', 'Slowly remove one accessory from your partner and kiss the skin underneath.', '{}'::jsonb),
  ('redflag', 3, 'They kiss along your jaw while you''re trying to finish a sentence.', 'Kiss along your partner''s jawline while they try to recite the alphabet.', '{}'::jsonb),
  ('redflag', 3, 'Your date gently bites your lower lip during the goodnight kiss.', 'Kiss your partner and gently bite their lower lip for two seconds.', '{}'::jsonb),
  ('redflag', 3, 'They slip a hand under your jacket just to hold your waist.', 'Slide your hands around your partner''s waist under their outer layer, over their shirt, for twenty seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your partner kisses the nape of your neck while you brush your teeth.', 'Kiss the nape of your partner''s neck slowly, three times.', '{}'::jsonb),
  ('redflag', 3, 'They breathe against your ear and say nothing, just to watch you react.', 'Breathe slowly against your partner''s ear for ten seconds without saying a word.', '{}'::jsonb),
  ('redflag', 3, 'Your partner tugs you in by your belt loops in public.', 'Pull your partner in by their belt loops or waistband and kiss them for five seconds.', '{}'::jsonb),
  ('redflag', 3, 'They kiss you against a wall outside the restaurant like a movie scene.', 'Back your partner gently against a wall and kiss them for ten seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your date slowly takes your jacket off before you''ve even sat down.', 'Slowly remove your partner''s outer layer, then kiss their shoulder once it''s off.', '{}'::jsonb),
  ('redflag', 3, 'They run a hand up your back and grip your nape during a kiss.', 'Kiss your partner while holding the nape of their neck for ten seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your partner straddles your lap at a party to ''fix your hair.''', 'Straddle your partner''s lap and run your fingers through their hair for twenty seconds.', '{}'::jsonb),
  ('redflag', 3, 'They slow-kiss your shoulder and just keep going toward your neck.', 'Kiss from your partner''s shoulder up to their ear, one slow kiss at a time.', '{}'::jsonb),
  ('redflag', 3, 'Your partner texts ''wear the thing I like'' before every date.', 'With your lips against your partner''s ear, tell them which outfit of theirs drives you crazy.', '{}'::jsonb),
  ('redflag', 3, 'They hold your waist with both hands every time they kiss you hello.', 'Hold your partner''s waist with both hands and kiss them for ten seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your date kisses the back of your knee while you''re lying on the couch.', 'Kiss the back of your partner''s knee, then their kneecap, slowly.', '{}'::jsonb),
  ('redflag', 3, 'They trace slow lines up your thigh during a movie, over your jeans.', 'Trace a slow line from your partner''s knee up to mid-thigh over their clothes for ten seconds.', '{}'::jsonb),
  ('redflag', 3, 'Your partner whispers that they can''t wait to get you home.', 'Hold your partner close, hands on their lower back, and whisper how tonight ends.', '{}'::jsonb),
  ('redflag', 3, 'They hold your jaw and stare at your lips before kissing you.', 'Hold your partner''s jaw, stare at their lips for five seconds, then kiss them slowly.', '{}'::jsonb),
  ('rate', 3, 'Rate how your partner''s hands feel on your waist.', 'Grip your partner''s waist and pull them close for twenty seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s slow kisses along your neck.', 'Kiss slowly from your partner''s ear down to their collarbone, taking ten seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s grip on your hips when they pull you in.', 'Hold your partner''s hips and pull them flush against you for fifteen seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate how your partner kisses your inner wrist.', 'Kiss your partner''s inner wrist slowly, holding eye contact for ten seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s ''I''ll tell you later'' whisper.', 'Whisper in your partner''s ear what you plan to do with them later.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s jaw kisses.', 'Kiss along your partner''s jawline from ear to chin, slowly.', '{}'::jsonb),
  ('rate', 3, 'Rate how your partner looks sitting on your lap, facing you.', 'Sit on your partner''s lap facing them and hold eye contact for thirty seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate how your partner pins your hands during a kiss.', 'Gently pin your partner''s wrists and kiss them for ten seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s hand on your thigh under the table.', 'Rest your hand on your partner''s thigh over their clothes and squeeze slowly for fifteen seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate how slowly your partner takes your jacket off.', 'Slowly remove one outer layer or accessory from your partner, then kiss their shoulder.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s kisses on the nape of your neck.', 'Kiss the nape of your partner''s neck slowly, three times.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s lip-biting during a kiss.', 'Kiss your partner and gently bite their lower lip for two seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s breath against your ear.', 'Breathe slowly against your partner''s ear for ten seconds without speaking.', '{}'::jsonb),
  ('rate', 3, 'Rate how your partner kisses you against a wall.', 'Back your partner gently against a wall and kiss them for ten seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s hands on your lower back during a long kiss.', 'Kiss your partner for fifteen seconds with both hands on their lower back.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s collarbone kisses.', 'Leave three slow kisses along your partner''s collarbone.', '{}'::jsonb),
  ('rate', 3, 'Rate the way your partner looks at your lips before a kiss.', 'Stare at your partner''s lips for five seconds, then kiss them slowly.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s grip on your nape when they kiss you.', 'Hold the nape of your partner''s neck and kiss them for ten seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s ability to make you forget where you are.', 'Kiss your partner for fifteen seconds with your hands on their hips.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s hands sliding up your back.', 'Slide your hands slowly up your partner''s back over their shirt, from waist to shoulders.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s knee-to-thigh trail over your jeans.', 'Trace a slow line from your partner''s knee to mid-thigh over their clothes for ten seconds.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s ''come home now'' texts.', 'Whisper the exact text you''d send your partner to get them home early.', '{}'::jsonb),
  ('rate', 3, 'Rate your partner''s shoulder-to-ear kiss trail.', 'Kiss from your partner''s shoulder up to their ear, one slow kiss at a time.', '{}'::jsonb),
  ('rate', 3, 'Rate the tension when your partner sits behind you holding your waist.', 'Sit behind your partner, arms around their waist, and kiss their neck once.', '{}'::jsonb),
  ('rate', 3, 'Rate how your partner says your name when they want you.', 'Say your partner''s name low in their ear, then kiss just below it.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever left a hickey on my partner''s neck.', 'Press a slow, lingering kiss to the side of your partner''s neck for ten seconds, just short of a hickey.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever pinned my partner against a wall to kiss them.', 'Back your partner against the nearest wall and kiss them for fifteen seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever been caught making out with my partner.', 'Kiss your partner for ten seconds as if someone might walk in.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever kissed my partner somewhere we definitely could have been caught.', 'Kiss your partner''s neck for ten seconds while they try to keep a straight face.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever taken off a layer of clothing just to tease my partner.', 'Remove one layer, like a jacket or socks, slowly while your partner watches.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever slid my hand up my partner''s thigh under the table.', 'Slide your hand slowly from your partner''s knee to mid thigh and hold it there for ten seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever made out with my partner in a changing room.', 'Make out with your partner for twenty seconds with your hands on their hips.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever grabbed my partner''s hips and pulled them against me.', 'Grab your partner''s hips and pull them flush against you for ten seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever kissed my partner''s thigh just above the knee.', 'Kiss your partner''s thigh just above the knee, over their clothes, three times.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever ditched a party early because we couldn''t keep our hands off each other.', 'Whisper exactly why you''d leave this party early, then kiss your partner''s ear.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever made out with my partner in a bathroom at someone else''s house.', 'Kiss your partner like you have thirty seconds before someone knocks.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever lifted my partner onto a counter while kissing them.', 'Pull your partner onto your lap and kiss them for fifteen seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever slid my hands under my partner''s shirt onto their lower back.', 'Slide your hands under the hem of your partner''s shirt to their lower back for ten seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever gently bitten my partner''s neck and loved their reaction.', 'Gently graze your teeth along your partner''s neck for five seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever fogged up car windows with my partner.', 'Kiss your partner for thirty seconds without breaking contact.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever had to fix my hair after a kiss before walking into a room.', 'Run both hands into your partner''s hair and kiss them until it''s messy.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever undone my partner''s top button just to kiss their collarbone.', 'Undo your partner''s top button and kiss their collarbone for five seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever kissed my partner in the rain until we were soaked.', 'Hold your partner''s jaw and kiss them for fifteen seconds like it''s pouring.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever been told to get a room.', 'Kiss your partner for twenty seconds like you''re about to hear "get a room."', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever traced my partner''s spine with my lips.', 'Kiss slowly down your partner''s spine over their shirt, from the nape to the lower back.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever made out with my partner on a balcony or rooftop.', 'Stand behind your partner, hands on their waist, and kiss their neck for fifteen seconds.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever hidden a hickey from my partner under a scarf or collar.', 'Kiss your partner''s collarbone slowly for ten seconds, right where a collar would cover it.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever wrapped my legs around my partner''s waist while kissing.', 'Wrap one leg around your partner''s and pull them close for a ten second kiss.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever kissed my partner breathless in a quiet corner of a crowded place.', 'Kiss your partner until one of you has to come up for air.', '{}'::jsonb),
  ('nhie', 3, 'Never have I ever whispered something so bold that my partner and I had to leave right away.', 'Press your lips to your partner''s ear and whisper your boldest thought about them.', '{}'::jsonb),
  ('bodypart', 3, 'Kiss the side of their neck, slow and open-mouthed. Stay there ten seconds.', 'Graze your teeth gently along their neck for 3 seconds, then kiss it.', '{"zone": "neck"}'::jsonb),
  ('bodypart', 3, 'Sweep their hair aside and kiss the nape of their neck. Slow. Then slower.', 'Kiss the nape of their neck five times, a little lower each time.', '{"zone": "nape"}'::jsonb),
  ('bodypart', 3, 'Kiss slowly along their jaw to just under the ear. Stop. Breathe. Do it again.', 'Hold their jaw in both hands and kiss them on the lips for 10 seconds.', '{"zone": "jaw"}'::jsonb),
  ('bodypart', 3, 'Kiss the hollow at the base of their throat, then follow their collarbone out.', 'Leave three lingering kisses on their collarbone, 3 seconds each.', '{"zone": "collarbone"}'::jsonb),
  ('bodypart', 3, 'Kiss the inside of their wrist and let your lips drag slowly toward the elbow.', 'Pin their wrist gently to the wall above them for 10 seconds while you kiss their neck.', '{"zone": "wrist"}'::jsonb),
  ('bodypart', 3, 'Slip your fingertips just under the hem at their lower back. Rest them on bare skin.', 'Trace slow circles on their lower back with your fingertips for 20 seconds.', '{"zone": "lowerback"}'::jsonb),
  ('bodypart', 3, 'Grip their waist with both hands and pull them flush against you. Hold it.', 'Hold them by the waist and kiss them on the lips for 10 seconds.', '{"zone": "waist"}'::jsonb),
  ('bodypart', 3, 'Hold their hips with both hands and pull them close. Slow and deliberate.', 'Press your thumbs into their hip bones, over clothes, while you kiss their neck for 5 seconds.', '{"zone": "hip"}'::jsonb),
  ('bodypart', 3, 'Slide your palm up their thigh, over clothes, slow. Stop halfway. Leave it there.', 'Keep your hand on their thigh, over clothes, and kiss their neck for 10 seconds.', '{"zone": "thigh"}'::jsonb),
  ('bodypart', 3, 'Kiss the back of their knee. Slow. Let them feel your breath before your lips.', 'Stroke behind their knee with your fingertips for 15 seconds.', '{"zone": "knee"}'::jsonb),
  ('bodypart', 3, 'Kiss them slow and deep, one hand on their jaw. Do not rush. Ten seconds minimum.', 'Kiss them for a full 20 seconds without letting go.', '{"zone": "lips"}'::jsonb),
  ('bodypart', 3, 'Catch their bottom lip gently between yours and hold it. Then let go, slow.', 'Kiss them on the lips three times, each one longer than the last.', '{"zone": "lips"}'::jsonb),
  ('bodypart', 3, 'Kiss the spot just behind their ear, then whisper exactly what you want next.', 'Nibble their earlobe gently for 3 seconds, then kiss their neck.', '{"zone": "ear"}'::jsonb),
  ('bodypart', 3, 'Ease their collar aside and kiss the bare curve of their shoulder.', 'Kiss from their shoulder to their neck, five slow kisses.', '{"zone": "shoulder"}'::jsonb),
  ('bodypart', 3, 'Stand behind them and kiss down the top of their spine. Three slow kisses.', 'Wrap your arms around them from behind and kiss their shoulder for 5 seconds.', '{"zone": "upperback"}'::jsonb),
  ('bodypart', 3, 'Kiss their thigh just above the knee, over clothes, and hold it three seconds.', 'Trace a slow line up their thigh with your fingertips, over clothes, for 10 seconds.', '{"zone": "thigh"}'::jsonb),
  ('bodypart', 3, 'Kiss your way up their calf, ankle to knee. Five slow kisses.', 'Stroke both calves with your palms for 20 seconds.', '{"zone": "calf"}'::jsonb),
  ('bodypart', 3, 'Kiss their neck, then graze it with your teeth. Gently. Just once.', 'Kiss their neck for 15 seconds while holding their waist.', '{"zone": "neck"}'::jsonb),
  ('bodypart', 3, 'Hook your thumbs in their belt loops at the hip, pull them in, and kiss them.', 'Keep your hands on their hips and kiss them for 10 seconds.', '{"zone": "hip"}'::jsonb),
  ('bodypart', 3, 'Wrap your arms around their waist from behind and kiss their neck. Slow.', 'Sway with them from behind, arms around their waist, for 30 seconds.', '{"zone": "waist"}'::jsonb),
  ('bodypart', 3, 'Press your palm firm at the small of their back and kiss them like the night depends on it.', 'Back them gently against a wall, hand on their lower back, and kiss them for 10 seconds.', '{"zone": "lowerback"}'::jsonb),
  ('bodypart', 3, 'Kiss from their cheek to their jaw to their neck without once lifting your lips.', 'Repeat it on the other side, cheek to neck, slow.', '{"zone": "cheek"}'::jsonb),
  ('bodypart', 3, 'Kiss the top of their foot, then the ankle. Slow. Look up at them while you do.', 'Kiss from their ankle to their knee, five slow kisses.', '{"zone": "foot"}'::jsonb),
  ('bodypart', 3, 'Drag your fingernails down their upper arm, shoulder to elbow. Then kiss the trail.', 'Kiss their upper arm three times, then their shoulder for 3 seconds.', '{"zone": "upperarm"}'::jsonb),
  ('bodypart', 3, 'Press your forehead to theirs, lips an inch apart. Hold ten seconds. No kiss.', 'After the ten seconds, kiss them on the lips for 5 seconds.', '{"zone": "forehead"}'::jsonb),
  ('charades', 3, 'Unzipping a dress with your teeth... failing', 'Kiss the nape of their neck for 5 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Pinned against the door after date night', 'Back them gently against a wall and kiss them for 10 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Peeling off skinny jeans gracefully. Not gracefully.', 'Run your palm up their thigh, over clothes, for 5 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Ripping a shirt open, buttons flying everywhere', 'Kiss their collarbone for 5 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Carrying them to bed and hitting every wall', 'Hold them by the waist and kiss them for 10 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Seductively pulling off a tie... and choking yourself', 'Pull them in by the collar and kiss their neck for 5 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Sliding into bed with a rose in your teeth', 'Kiss the inside of their wrist, then up to the elbow.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Trying to be sexy when your leg cramps', 'Rub their calf slowly for 20 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Kissing all the way up the stairs, tripping on every step', 'Kiss them on the lips for 10 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Making out in a car and honking the horn by accident', 'Kiss their jaw, ear to chin, slow.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Blindfolded, guessing where the next kiss lands', 'Close their eyes and kiss three spots: wrist, neck, shoulder.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Massage oil bottle exploding mid massage', 'Massage their shoulders for 30 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Hotel key card won''t work and you can''t stop kissing', 'Kiss their neck for 10 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Pulling them in by the belt for a kiss', 'Hook your finger in their belt loop, pull them close, kiss for 5 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Lighting mood candles and setting off the smoke alarm', 'Kiss their earlobe, then the spot behind their ear.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Throwing your shirt across the room. It lands on the fan.', 'Kiss the top of their shoulder for 3 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Breakfast in bed that turns into skipping breakfast', 'Kiss them slowly for 10 seconds.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Sneaking into bed at 2 a.m. and accidentally waking them', 'Kiss their forehead, cheek, then lips, 2 seconds each.', '{"category": "Bedroom Charade"}'::jsonb),
  ('charades', 3, 'Hiding under the covers when the doorbell rings', 'Hold their hips and kiss their neck for 5 seconds.', '{"category": "Scenario"}'::jsonb),
  ('charades', 3, 'Fifty Shades: the ''Laters, baby'' elevator moment', 'Pin their wrists gently to the wall and kiss them for 5 seconds.', '{"category": "Movie"}'::jsonb),
  ('charades', 3, 'Mr. and Mrs. Smith: the fight that turns into kissing', 'Grab them by the waist and kiss them for 10 seconds.', '{"category": "Movie"}'::jsonb),
  ('charades', 3, 'Magic Mike: the rain dance, fully clothed', 'Slow dance with them, hands on their hips, for 20 seconds.', '{"category": "Movie"}'::jsonb),
  ('charades', 3, 'Pony by Ginuwine, full routine', 'Kiss behind their knee or their inner wrist, your choice, 3 seconds.', '{"category": "Song"}'::jsonb),
  ('charades', 3, 'Earned It by The Weeknd', 'Trace slow circles on their lower back for 15 seconds.', '{"category": "Song"}'::jsonb),
  ('charades', 3, 'Marilyn singing ''Happy Birthday, Mr. President''', 'Whisper in their ear, then kiss their neck for 5 seconds.', '{"category": "Celebrity"}'::jsonb),
  ('wyr', 3, 'Would you rather have your neck kissed for a minute or have your thighs traced for a minute?', 'Trace slow lines along your partner''s thighs, over clothes, for one minute.', '{"a": "Have your neck kissed for a minute", "b": "Have your thighs traced for a minute"}'::jsonb),
  ('wyr', 3, 'Would you rather be pinned to the bed by your wrists or pin your partner down by their wrists?', 'Gently pin your partner''s wrists above their head and kiss their neck for 30 seconds.', '{"a": "Be pinned to the bed by your wrists", "b": "Pin your partner down by their wrists"}'::jsonb),
  ('wyr', 3, 'Would you rather be blindfolded and kissed somewhere new or blindfold your partner and choose the spot?', 'Cover your partner''s eyes and kiss three surprise spots: inner wrist, collarbone, nape. 5 seconds each.', '{"a": "Be blindfolded and kissed somewhere new", "b": "Blindfold your partner and choose the spot"}'::jsonb),
  ('wyr', 3, 'Would you rather have your wrists tied with a soft scarf or tie your partner''s wrists with a soft scarf?', 'Loosely loop a scarf around your partner''s wrists and kiss along their jaw for 30 seconds.', '{"a": "Have your wrists tied with a soft scarf", "b": "Tie your partner''s wrists with a soft scarf"}'::jsonb),
  ('wyr', 3, 'Would you rather have your jacket slowly taken off you or slowly take off your partner''s hoodie?', 'Slowly remove one outer layer from your partner, like a jacket or hoodie, kissing their neck as you go.', '{"a": "Have your jacket slowly taken off you", "b": "Slowly take off your partner''s hoodie"}'::jsonb),
  ('wyr', 3, 'Would you rather have your hips gripped while you kiss or have your thighs squeezed while you kiss?', 'Hold your partner''s hips firmly and kiss them for 30 seconds.', '{"a": "Have your hips gripped while you kiss", "b": "Have your thighs squeezed while you kiss"}'::jsonb),
  ('wyr', 3, 'Would you rather whisper your boldest fantasy or hear your partner''s boldest fantasy whispered?', 'Whisper one fantasy into your partner''s ear, then kiss behind that ear for 5 seconds.', '{"a": "Whisper your boldest fantasy", "b": "Hear your partner''s boldest fantasy whispered"}'::jsonb),
  ('wyr', 3, 'Would you rather have kisses trailed from ear to collarbone or have kisses trailed from wrist to shoulder?', 'Trail slow kisses from your partner''s ear down to their collarbone, taking 20 seconds.', '{"a": "Have kisses trailed from ear to collarbone", "b": "Have kisses trailed from wrist to shoulder"}'::jsonb),
  ('wyr', 3, 'Would you rather be in total control for five minutes or give up total control for five minutes?', 'Take the lead for 2 minutes: you decide where your partner''s hands rest, waist, hips, or thighs.', '{"a": "Be in total control for five minutes", "b": "Give up total control for five minutes"}'::jsonb),
  ('wyr', 3, 'Would you rather have a hand slide slowly up your thigh or have a hand slide around your lower back?', 'Slide your hand slowly up your partner''s thigh, over clothes, and rest it at mid thigh for 10 seconds.', '{"a": "Have a hand slide slowly up your thigh", "b": "Have a hand slide around your lower back"}'::jsonb),
  ('wyr', 3, 'Would you rather be kissed blindfolded with no warning or be kissed with your hands held behind you?', 'Hold your partner''s hands behind their back and kiss them for 30 seconds.', '{"a": "Be kissed blindfolded with no warning", "b": "Be kissed with your hands held behind you"}'::jsonb),
  ('wyr', 3, 'Would you rather have your hip bones kissed over your clothes or have your lower back kissed over your clothes?', 'Kneel and kiss your partner''s hip bone over their clothes for 10 seconds.', '{"a": "Have your hip bones kissed over your clothes", "b": "Have your lower back kissed over your clothes"}'::jsonb),
  ('wyr', 3, 'Would you rather be pressed against a door and kissed or be pulled onto a lap and kissed?', 'Press your partner against a door and kiss their neck for 30 seconds.', '{"a": "Be pressed against a door and kissed", "b": "Be pulled onto a lap and kissed"}'::jsonb),
  ('wyr', 3, 'Would you rather act out a fantasy tonight or hear a fantasy described tonight?', 'Describe a fantasy setting in your partner''s ear for 30 seconds, then kiss their lips.', '{"a": "Act out a fantasy tonight", "b": "Hear a fantasy described tonight"}'::jsonb),
  ('wyr', 3, 'Would you rather have your waist grabbed and pulled close or have your hips guided onto a lap?', 'Grab your partner''s waist, pull them flush against you, and hold for 20 seconds.', '{"a": "Have your waist grabbed and pulled close", "b": "Have your hips guided onto a lap"}'::jsonb),
  ('wyr', 3, 'Would you rather be told exactly where you''ll be kissed or never know where the next kiss lands?', 'Tell your partner three places you''ll kiss them, then kiss each for 5 seconds.', '{"a": "Be told exactly where you''ll be kissed", "b": "Never know where the next kiss lands"}'::jsonb),
  ('wyr', 3, 'Would you rather get a full body massage with oil or get a slow thigh and hip massage?', 'Massage your partner''s thighs and hips, over clothes, for two minutes.', '{"a": "Get a full body massage with oil", "b": "Get a slow thigh and hip massage"}'::jsonb),
  ('wyr', 3, 'Would you rather make out until someone has to stop or kiss for one minute without breaking?', 'Make out for 90 seconds. First to pull away owes a 10 second kiss on the neck.', '{"a": "Make out until someone has to stop", "b": "Kiss for one minute without breaking"}'::jsonb),
  ('wyr', 3, 'Would you rather be blindfolded for ten minutes or have your hands tied for ten minutes?', 'Blindfold your partner for one minute and kiss their lips, jaw, and neck in any order.', '{"a": "Be blindfolded for ten minutes", "b": "Have your hands tied for ten minutes"}'::jsonb),
  ('wyr', 3, 'Would you rather have your nape kissed while held from behind or have your jaw kissed while pinned to a wall?', 'Hold your partner from behind and kiss the nape of their neck for 30 seconds.', '{"a": "Have your nape kissed while held from behind", "b": "Have your jaw kissed while pinned to a wall"}'::jsonb),
  ('wyr', 3, 'Would you rather take off one outer layer while being watched or watch your partner take off one outer layer?', 'Slowly take off one outer layer, like a jacket or hoodie, while holding eye contact with your partner.', '{"a": "Take off one outer layer while being watched", "b": "Watch your partner take off one outer layer"}'::jsonb),
  ('wyr', 3, 'Would you rather have teeth graze your neck or have teeth graze your shoulder?', 'Lightly graze your teeth along your partner''s neck for 5 seconds, then kiss the spot.', '{"a": "Have teeth graze your neck", "b": "Have teeth graze your shoulder"}'::jsonb),
  ('wyr', 3, 'Would you rather be pinned to the couch for a kiss or be lifted onto a counter for a kiss?', 'Lean your partner back onto the couch and kiss them for 30 seconds.', '{"a": "Be pinned to the couch for a kiss", "b": "Be lifted onto a counter for a kiss"}'::jsonb),
  ('wyr', 3, 'Would you rather be whispered to while pinned in place or be kissed while you can''t use your hands?', 'Hold your partner''s wrists at their sides and whisper what you want into their ear for 20 seconds.', '{"a": "Be whispered to while pinned in place", "b": "Be kissed while you can''t use your hands"}'::jsonb),
  ('wyr', 3, 'Would you rather have your waist kissed through your shirt or have your thighs kissed through your jeans?', 'Kiss your partner''s waist through their shirt, side to side, for 20 seconds.', '{"a": "Have your waist kissed through your shirt", "b": "Have your thighs kissed through your jeans"}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to leave a hickey somewhere visible?', 'Kiss your partner''s neck slowly for ten seconds, right where a hickey would show.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to push their partner up against a wall for a kiss?', 'Back your partner against a wall and kiss them for fifteen seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to get caught kissing in the bathroom at a party?', 'Kiss your partner for twenty seconds like someone is about to knock.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to suggest kissing somewhere risky?', 'Kiss your partner in the spot in this room where you''d most likely get caught, for ten seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to take off a layer just to see their partner''s reaction?', 'Remove one layer slowly, like a jacket or socks, while holding eye contact.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to slide a hand up their partner''s thigh at dinner?', 'Slide your hand from your partner''s knee to mid thigh and leave it there for fifteen seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to fog up the car windows?', 'Kiss your partner without breaking for thirty seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to pull their partner in by the hips without warning?', 'Pull your partner in by the hips and hold them flush against you for ten seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to sneak into a changing room together?', 'Kiss your partner for fifteen seconds with your hands on their lower back.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to make the party end early for both of them?', 'Whisper into your partner''s ear the reason you''d leave right now.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to kiss their partner breathless in a stairwell?', 'Kiss your partner until one of you needs to breathe.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to lift their partner onto a table mid kiss?', 'Pull your partner onto your lap facing you and kiss them for ten seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to slip their hands under their partner''s shirt onto their back?', 'Slide your hands under the hem of your partner''s shirt onto their lower back for ten seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to graze their teeth along their partner''s neck?', 'Gently graze your teeth along your partner''s neck from ear to shoulder.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to get told to get a room by their friends?', 'Kiss your partner the way that would get you told to get a room, for fifteen seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to ruin their partner''s hair with one kiss?', 'Slide your hands into your partner''s hair and kiss them until it''s a mess.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to unbutton their partner''s collar to kiss their collarbone?', 'Undo your partner''s top button and kiss their collarbone for five seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to kiss all the way down their partner''s spine?', 'Kiss down your partner''s spine over their shirt, from the nape to the lower back.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to make out on a rooftop at midnight?', 'Stand behind your partner, hands on their hips, and kiss their neck for fifteen seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to wear a hickey proudly the next day?', 'Kiss your partner''s collarbone slowly for ten seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to wrap their legs around their partner''s waist?', 'Sit on your partner''s lap and wrap your legs around their waist for twenty seconds.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to whisper something that makes their partner want to leave immediately?', 'Press your lips to your partner''s ear and whisper your boldest thought about them.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to kiss their partner in a hotel hallway before reaching the room?', 'Kiss your partner against a door for fifteen seconds like you can''t find the key.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to keep kissing after the elevator doors open?', 'Kiss your partner for ten seconds, then five more after they start laughing.', '{}'::jsonb),
  ('mostlikely', 3, 'Who''s most likely to sit facing their partner on their lap during a movie?', 'Sit facing your partner on their lap, hands on their shoulders, for thirty seconds.', '{}'::jsonb),
  ('hotseat', 3, 'Where on my body do I most want to be kissed right now?', 'Kiss that spot, over clothes, for 20 seconds. Keep it to neck, jaw, collarbone, waist, hips, or thighs.', '{}'::jsonb),
  ('hotseat', 3, 'Would I rather pin you down or be pinned down?', 'Gently pin your partner''s wrists and kiss their neck for 30 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'What''s a fantasy I''ve never fully told you about?', 'Whisper the first line of it, then kiss your partner''s ear.', '{}'::jsonb),
  ('hotseat', 3, 'How would I react if you blindfolded me right now?', 'Cover your partner''s eyes for one minute and kiss three spots: jaw, nape, inner wrist.', '{}'::jsonb),
  ('hotseat', 3, 'Do I want your hands on my hips or my thighs when we kiss?', 'Grip your partner''s hips or thighs, whichever they guessed, over clothes, and kiss them for 30 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'Which outer layer of yours would I most like to take off you?', 'Let your partner slowly remove it while kissing your neck.', '{}'::jsonb),
  ('hotseat', 3, 'Would I like having my wrists tied with something soft?', 'Loosely loop a scarf around your partner''s wrists and kiss their jaw for 30 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'Where would I most want you to leave a slow trail of kisses?', 'Trail kisses there, over clothes, for 30 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'What''s the boldest place I''d want to kiss you in public?', 'Kiss your partner''s neck for 10 seconds like someone might walk in.', '{}'::jsonb),
  ('hotseat', 3, 'Do I like it more when you take control or when I do?', 'Whoever is in control places the other''s hands on their hips for one minute.', '{}'::jsonb),
  ('hotseat', 3, 'What''s one thing I want you to do to me tonight that I haven''t asked for?', 'Whisper your answer, then kiss your partner''s collarbone.', '{}'::jsonb),
  ('hotseat', 3, 'How high up my thigh would I let your hand go under the dinner table?', 'Rest your hand on your partner''s thigh, over clothes, for one minute.', '{}'::jsonb),
  ('hotseat', 3, 'What''s my favorite way for you to hold me while we make out?', 'Hold your partner that way and make out for 30 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'Would I rather be kissed slowly blindfolded or fast with my hands held?', 'Do whichever they guessed for 20 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'Which room have I most imagined pinning you against a wall in?', 'Back your partner against the nearest wall and kiss them for 30 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'What''s the one spot that makes me lose focus when you kiss it?', 'Kiss your partner''s neck, jaw, and ear, 5 seconds each, until you find it.', '{}'::jsonb),
  ('hotseat', 3, 'How long could I last blindfolded before I''d reach for you?', 'Blindfold your partner for one minute and trace their jaw and neck with your fingertips.', '{}'::jsonb),
  ('hotseat', 3, 'What would I want you to say while you pin me against the wall?', 'Pin your partner to the wall and say it into their ear.', '{}'::jsonb),
  ('hotseat', 3, 'Would I want my jacket taken off slowly or pulled off fast?', 'Remove one outer layer from your partner the way they guessed.', '{}'::jsonb),
  ('hotseat', 3, 'What role would I want to play in a fantasy date with you?', 'Play that role for 30 seconds and end it with a kiss on your partner''s neck.', '{}'::jsonb),
  ('hotseat', 3, 'Where would I want your lips if my hands were tied?', 'Hold your partner''s hands behind their back and kiss their neck or collarbone for 20 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'What''s the hottest thing you''ve ever done to me, in my opinion?', 'Recreate it as a 20 second kiss on your partner''s neck.', '{}'::jsonb),
  ('hotseat', 3, 'Do I like my hips pulled into you or my lower back held?', 'Do whichever they guessed while kissing them for 20 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'What do I picture when I imagine you pinning me down?', 'Gently pin your partner''s hips and kiss their jaw for 20 seconds.', '{}'::jsonb),
  ('hotseat', 3, 'What would I do if you gave me total control for ten minutes?', 'Give your partner control for 2 minutes. They direct where your lips go, neck and up.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the steamiest kiss of your life.', 'Give your partner the steamiest kiss you''ve got, twenty seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the best place you''ve ever been kissed on your body.', 'Kiss your partner on the body part you''d most like kissed tonight, above the waist and not the chest.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the riskiest place you''ve ever kissed someone.', 'Kiss your partner''s neck while they try to stay completely still.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about a fantasy you''ve never said out loud.', 'Whisper one detail of a fantasy into your partner''s ear, lips touching it.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about what drives you absolutely wild.', 'Do the thing that drives your partner wild for ten seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the most public place you''ve gotten handsy.', 'Run your hands from your partner''s waist to their hips and hold them there for ten seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about your inner thighs and how ticklish they are.', 'Rest your hand on your partner''s inner knee and slide it up two inches. Stop there.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about a time you almost got caught.', 'Kiss your partner like you might get caught any second, fifteen seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the boldest thing you''ve ever whispered to someone.', 'Whisper the boldest thing you can think of to your partner, then kiss their ear.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about a role you''d love to play for one night.', 'Stay in character as that role and kiss your partner''s hand like you mean it.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the hottest text you''ve ever sent.', 'Say your hottest text out loud, slowly, inches from your partner''s lips.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about your lower back and what happens when it''s touched.', 'Slide your hand under the hem of your partner''s shirt to rest on their lower back for ten seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the most intense eye contact you''ve ever had.', 'Hold eye contact with your partner for thirty seconds, then kiss them.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about a place you''d love to be kissed but never have been.', 'Kiss your partner''s hip bone through their clothes.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the most turned-on you''ve been in public.', 'Kiss your partner''s neck while your hand rests on their thigh, ten seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about your hips and how you like them held.', 'Pull your partner in by their hips and kiss them for ten seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about a dream about your partner you never told them.', 'Recreate one innocent moment from that dream, ending with a kiss on the neck.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the best kiss you''ve had in a car.', 'Kiss your partner while holding their jaw, fifteen seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about what your partner does that makes you lose focus.', 'Kiss a slow trail from your partner''s jaw down to their collarbone.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the longest you''ve ever gone without a kiss and how it ended.', 'Make your partner wait ten seconds with your lips almost on theirs, then kiss them.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about your wildest kiss in the dark.', 'Close your eyes and find your partner''s lips using only your hands on their face.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the most electric touch you''ve ever felt.', 'Trace your partner''s inner wrist up to their elbow with your lips.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the spot that makes you forget your own name.', 'Kiss that spot on your partner, as long as they let you, up to twenty seconds.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about the boldest move you''ve made on a first night together.', 'Pull your partner onto your lap for the next round, fully clothed.', '{}'::jsonb),
  ('twotruths', 3, 'Two truths and a spicy lie about a time you were seduced and loved it.', 'Seduce your partner using only kisses on the neck and ears, twenty seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe the steamiest kiss we''ve ever shared.', 'Recreate it now, twenty seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: tell me the best place I''ve ever kissed you on your body.', 'Kiss your partner there, if it''s above the waist and off the chest. Otherwise their neck.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe what drives you absolutely wild about me.', 'Do that to your partner for ten seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: name the riskiest place you''d let me kiss you.', 'Kiss your partner like you''re in that place, fifteen seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe a fantasy you have about us, keep it PG-13.', 'Whisper one more detail into your partner''s ear.', '{}'::jsonb),
  ('swap', 3, 'As your partner: tell me how you want me to kiss you tonight.', 'Kiss your partner that way, twenty seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe what you''d do if we were alone right now.', 'Do the PG-13 version of it for ten seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: say the spot that makes you lose control.', 'Kiss that spot on your partner, if it''s off-limits here, kiss their neck instead.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe how my hands feel on your thighs.', 'Rest your hand on your partner''s thigh and squeeze gently for ten seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: tell me the most public place you''d want to kiss me.', 'Kiss your partner like the whole room is watching.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe the hottest moment we''ve had in public.', 'Kiss your partner''s neck while holding their hips, ten seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: say what you think about when you look at my lips.', 'Kiss your partner, slow, then fast, then slow again.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe what my kisses on your lower back do to you.', 'Slide your hand under the hem of your partner''s shirt to their lower back for ten seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: tell me the outfit you''d love to take off me, piece by piece.', 'Remove one accessory from your partner, slowly, with your teeth or hands.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe the moment you get turned on by me.', 'Recreate that moment with a kiss on your partner''s neck.', '{}'::jsonb),
  ('swap', 3, 'As your partner: say the boldest thing you''ve wanted to say to me.', 'Say it now, lips against your partner''s ear.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe how you''d seduce me in three moves.', 'Do all three moves on your partner, PG-13.', '{}'::jsonb),
  ('swap', 3, 'As your partner: tell me where you want my lips next.', 'Kiss your partner there, above the waist and off the chest.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe what you''d whisper to me in the dark.', 'Whisper it with your lips on your partner''s neck.', '{}'::jsonb),
  ('swap', 3, 'As your partner: name the role you''d want me to play for one night.', 'Play that role for ten seconds and kiss your partner''s hand.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe the kiss that would win any argument.', 'Win an imaginary argument with your partner using one long kiss on the lips, ten seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: tell me how close you want me right now.', 'Pull your partner onto your lap, fully clothed, for one round.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe how you''d tease me if I couldn''t touch you.', 'Kiss your partner''s neck and jaw while they keep their hands behind their back, fifteen seconds.', '{}'::jsonb),
  ('swap', 3, 'As your partner: say the moment you realized I could drive you crazy.', 'Trail kisses from your partner''s inner wrist to their shoulder.', '{}'::jsonb),
  ('swap', 3, 'As your partner: describe how you''d want tonight to end, keep it PG-13.', 'Kiss your partner like it''s already ending that way, fifteen seconds.', '{}'::jsonb)
on conflict (game, text) do nothing;
