#!/usr/bin/env node
// Card pipeline: content/*.json -> lint -> dist/cards.json (Lv1 + Lv2 only) and,
// with --seed, supabase/seed/premium_cards.sql (Lv3 + the server-only taste cards).
// Lv3 text never reaches the client bundle: the build refuses to write it.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { GAMES } from '../lib/games.js';

const root = new URL('..', import.meta.url).pathname;
const errors = [];
const fail = (m) => errors.push(m);

const BANNED_GROUP = [/\bpartner/i, /\bboyfriend/i, /\bgirlfriend/i, /\bhusband/i, /\bwife\b/i, /\bwives\b/i, /\bbabe\b/i, /each other/i, /your other half/i, /you two/i];
const BANNED_RFGF = [...BANNED_GROUP, /\byour date\b/i];
const BANNED_NHIE = [...BANNED_GROUP, /\bus\b/i, /\bwe\b/i];
const MIN_PER_LEVEL = { redflag: 30, nhie: 30, charades: 30, mostlikely: 30, twotruths: 30 };
const CHARADE_CATS = ['Movie', 'TV Show', 'Song'];
const CHARADE_ORIGINS = ['Hollywood', 'Bollywood', 'Global'];

// The app's list must match the server's
const appCfg = readFileSync(join(root, 'public/js/config.js'), 'utf8');
const appGames = [...appCfg.matchAll(/\{ id: '(\w+)', mode: '(\w+)' \}/g)].map((m) => `${m[1]}:${m[2]}`).join(',');
if (appGames !== GAMES.map((g) => `${g.id}:${g.mode}`).join(',')) fail('public/js/config.js GAMES differs from lib/games.js');

const all = [];
const files = readdirSync(join(root, 'content')).filter((f) => f.endsWith('.json'));
for (const g of GAMES) if (!files.includes(g.id + '.json')) fail(`content/${g.id}.json missing`);
for (const f of files) {
  const id = f.replace('.json', '');
  const game = GAMES.find((g) => g.id === id);
  if (!game) { fail(`content/${f}: not a game in lib/games.js`); continue; }
  const cards = JSON.parse(readFileSync(join(root, 'content', f), 'utf8'));
  const seen = new Set();
  const per = { 1: 0, 2: 0, 3: 0 };
  let tastes = 0;
  for (const c of cards) {
    const where = `${f} "${String(c.text).slice(0, 50)}"`;
    if (c.game !== id) fail(`${where}: game is ${c.game}`);
    if (![1, 2, 3].includes(c.heat)) fail(`${where}: bad heat`);
    else per[c.heat]++;
    if (!c.text || typeof c.text !== 'string') fail(`${where}: no text`);
    const blob = [c.text, c.optionalDare, c.a, c.b].filter(Boolean).join(' ');
    if (/[\u2014\u2013]/.test(blob)) fail(`${where}: em/en dash`);
    if (seen.has(c.text.toLowerCase())) fail(`${where}: duplicate`);
    seen.add(c.text.toLowerCase());
    if (c.taste) { tastes++; if (c.heat !== 3) fail(`${where}: taste card must be Lv3`); }
    if (game.mode === 'group') {
      for (const re of BANNED_GROUP) if (re.test(blob)) fail(`${where}: group card uses ${re}`);
      if (c.optionalDare) fail(`${where}: group cards have no dares`);
    }
    if (id === 'redflag') for (const re of BANNED_RFGF) if (re.test(c.text)) fail(`${where}: scenario uses ${re}`);
    if (id === 'nhie') {
      for (const re of BANNED_NHIE) if (re.test(c.text)) fail(`${where}: statement uses ${re}`);
      if (!/^Never have I ever /.test(c.text)) fail(`${where}: must start "Never have I ever"`);
    }
    if (id === 'charades') {
      if (!CHARADE_CATS.includes(c.category)) fail(`${where}: category must be Movie / TV Show / Song`);
      if (!CHARADE_ORIGINS.includes(c.origin)) fail(`${where}: origin must be Hollywood / Bollywood / Global`);
      if (c.optionalDare) fail(`${where}: charades have no dares`);
    }
  }
  for (const h of [1, 2, 3]) if (MIN_PER_LEVEL[id] && per[h] < MIN_PER_LEVEL[id]) fail(`${f}: only ${per[h]} Lv${h} cards (need ${MIN_PER_LEVEL[id]})`);
  if (tastes !== 1) fail(`${f}: needs exactly one taste card (has ${tastes})`);
  all.push(...cards);
}

if (errors.length) {
  console.error('Card lint failed:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// Client deck: Lv1 + Lv2 only. Belt and braces: refuse to write anything hot.
const client = all.filter((c) => c.heat === 1 || c.heat === 2).map(({ taste, ...c }) => c);
if (client.some((c) => c.heat >= 3 || c.taste)) { console.error('refusing to ship Lv3 to the client'); process.exit(1); }
const out = process.argv.includes('--out') ? process.argv[process.argv.indexOf('--out') + 1] : null;
if (out) writeFileSync(out, JSON.stringify(client));

if (process.argv.includes('--seed')) {
  const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
  const rows = all.filter((c) => c.heat === 3).map((c) => {
    const extra = {};
    for (const k of ['a', 'b', 'category', 'origin']) if (c[k] != null) extra[k] = c[k];
    return `  (${q(c.game)}, 3, ${q(c.text)}, ${c.optionalDare ? q(c.optionalDare) : 'null'}, ${q(JSON.stringify(extra))}::jsonb, ${c.taste ? 'true' : 'false'})`;
  });
  const sql = `-- Heat Check: Lv3 (Hot) cards, served only by the server.\n-- Generated by tools/cards.mjs --seed from content/*.json. Do not edit by hand.\n-- Run after both migrations. Safe to re-run: existing cards are kept.\n\ninsert into public.premium_cards (game, heat, text, optional_dare, extra, is_taste)\nvalues\n${rows.join(',\n')}\non conflict (game, text) do update set is_taste = excluded.is_taste, extra = excluded.extra, optional_dare = excluded.optional_dare;\n`;
  writeFileSync(join(root, 'supabase/seed/premium_cards.sql'), sql);
}
const counts = GAMES.map((g) => `${g.id} ${all.filter((c) => c.game === g.id).length}`).join(', ');
console.log(`cards ok: ${client.length} client (Lv1-2), ${all.filter((c) => c.heat === 3).length} Lv3 server-only [${counts}]`);
